### ISSUE TITLE
Bee-Motion - Debugging

### ISSUE THREAD

**Issue by adamcaz** [strid3r21/Bee-Motion#1]
Hi strid3r21, I have purchased a few of these for my home and they look fantastic. I’ve flashed one with the deep sleep code provided from this repo and that seems to complete flashing successfully.
However, once the Esp32-S2 is not in flash mode any more I can’t seem to find a way to debug the code running on the board - I have no serial port any more to connect the Arduino IDE serial monitor to. Any pointers on how to debug this device while I test the code thanks?

**Comment by strid3r21** [comment]
Hi Adam,

Yes this is an easy fix thankfully. Just go to the tools menu in the
Arduino ide and down to USB CDC on boot and enable that. Then reflash your
code again with that enabled.

In the readme you can see a guide on
it. https://github.com/strid3r21/Bee-Motion

Cheers.,

Paul

**Comment by adamcaz** [comment]
Hi Paul, sorry I should have said that I have already turned that on before flashing..

Once flashing has finished and I reset the device no device is detected (and no COM ports) in Windows at all. It’s only if I put it back into flashing mode that I get an ESP32-S2 device and a COM port again in Device Manager..

I’ve tried two different Windows 10 machines now with Arduino 1.8 and 2.04RC and it’s the same problem! :)

**Comment by strid3r21** [comment]
huh, the USB CDC option controls that functionality, so thats weird it still doesnt work. have you tried more than one of your boards to see if they all do the same thing? and if so can you attach a screenshot of your tools menu so i can look it over and see if there is something that sticks out that could be causing your issue.

if you're able to flash them then you should be able to use the serial port for debugging, so there is something on the software side of things that is causing the issue.

**Comment by adamcaz** [comment]
Thanks Paul. I’ll keep investigating.
One last thing - what pin is the internal LED on thanks? Would be great to turn this on and off..

**Comment by strid3r21** [comment]
> Thanks Paul. I’ll keep investigating.
> One last thing - what pin is the internal LED on thanks? Would be great to turn this on and off..

One last thing you can try to get the serial monitor to work is to connect the board to the PC, open up the serial monitor and then hit the reset button on the board. I've found that works for me consistently, but let me know if you continue to have trouble with it.

The LED on the board is only a battery charge status LED and isn't connected to any pins. 

It will blink randomly when the USB is plugged in but with no battery connected because it's essentially searching for a battery when one isn't plugged in. It will stay solid when it's charging a lipo battery via USB and then it will go off once the battery is fully charged.

**Comment by adamcaz** [comment]
Hi Paul, sorry to say I’m still having trouble getting this to run.

Could you help me code up a simple MQTT example where Motion activated a wifi connect and send a msg to a specific MQTT server & topic?

I bought a few and it would be great to get them working.. :)

Many thanks,

Adam Carroll.
P: 0405 252 300
E: ***@***.******@***.***>
--
